# 判断机器学习的算法的性能

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train_test_split

In [6]:
shuffle_indexes = np.random.permutation(len(X)) # 对数据集的索引进行shuffle操作

In [7]:
shuffle_indexes

array([129, 101,  58,  89,  95,  31,  46,  79,  13,  82, 148,  29,  70,
       142,  93, 107,  78, 135,  90,  56, 143, 144,   3, 128,  15,  35,
        72,  16,  14,  41, 114,  63, 137,  67, 106,  48,  61, 116, 130,
        80,  52, 117, 136,  54, 125,   9,  18,  64, 110,  24, 111, 124,
        60,  30,  45,  49, 139, 104,  20,   4,  51,  73,  71, 149,  36,
       113, 122, 138,  66,  23, 120,  57,  32, 115,  59,  96,  44, 146,
        43,  88, 147,   0,  19,  28,  55,  76,  77,  34,  97, 132,  98,
        91,  68,  85,   1, 112, 121, 102,   5,  62,  12,  25,   6,  65,
        42,  10, 100,  94,  26,  83, 118,  11,   2, 134,  86, 108, 109,
        81,  75,   7,  92,  84, 133, 126,  37,  17, 119,  69,  53, 123,
        74,  87,  21, 141,  47, 145, 105,  27,  22, 127, 131,  50, 140,
        39,  99,  33,   8, 103,  40,  38])

In [8]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [9]:
test_size

30

In [10]:
test_indexes = shuffle_indexes[: test_size]
train_indexes = shuffle_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 使用我们的算法

In [14]:
from playML.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X ,y)

In [16]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [18]:
from playML.kNN import KNNClassifier

In [19]:
my_knn_clf = KNNClassifier(k=3)

In [20]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [21]:
y_predict = my_knn_clf.predict(X_test)

In [22]:
y_predict

array([0, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 0, 1, 0,
       2, 2, 1, 0, 2, 0, 1, 1])

In [23]:
y_test

array([0, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 0, 2, 0,
       2, 2, 1, 0, 2, 0, 1, 1])

In [24]:
sum(y_predict == y_test)

29

In [25]:
# 对比预测结果准确率
sum(y_predict == y_test)/len(y_test)

0.9666666666666667

## sklearn中的train_test_split

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=666)

In [28]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [29]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
